name: Build Staging (Develop)

on:
  push:
    branches: [ develop ]

jobs:
  # Build and validate staging
  build-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build for staging
        run: npm run build
        
      - name: Upload staging artifacts
        uses: actions/upload-artifact@v4
        with:
          name: staging-build
          path: dist/
          retention-days: 7
          
      - name: Staging build completed
        run: |
          echo "✅ Staging build completed successfully!"
          echo "📦 Build artifacts available for download"
          echo "🔗 To deploy staging: merge develop → main"
          echo ""
          echo "Staging changes ready for review:"
          echo "- Banner de staging agregado"
          echo "- Estilos y animaciones actualizados"
          echo "- JavaScript mejorado"