name: Deploy to Staging (Develop)

on:
  push:
    branches: [ develop ]

# Sets permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build and test staging
  build-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build for staging
        run: npm run build
        
      - name: Upload staging artifacts
        uses: actions/upload-artifact@v4
        with:
          name: staging-build
          path: dist/
          
      - name: Deploy to GitHub Pages Staging
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: staging
          keep_files: true
          
      - name: Staging deployment completed
        run: |
          echo "✅ Staging deployed to GitHub Pages!"
          echo "🔗 URL: https://juanpalacioscmd.github.io/taller-mecanico-landing/staging/"